"""empty message

Revision ID: 6b31b47a27fb
Revises: 8df929f775ed
Create Date: 2022-07-16 14:18:29.501590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b31b47a27fb'
down_revision = '8df929f775ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Beaches', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Beaches', 'address')
    # ### end Alembic commands ###
